<a href="https://colab.research.google.com/github/benafshapostwala/Accident-Severity-Prediction/blob/main/Data_Mining_CW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing and mounting google drive as we have stored the data in a folder here (saved in email id benbakes21@gmail.com)
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
#importing the excel file containing the data using pandas
import pandas as pd
data = pd.ExcelFile('/content/gdrive/My Drive/Data_mining_cw2_data/LendingClubLoans2018-2020.xlsx')

In [4]:
#converting excel file to pandas dataframe
lending_data=pd.read_excel(data)

In [7]:
#inspecting the first 5 rows of the dataframe
lending_data.head()

          id  ... orig_projected_additional_accrued_interest
0  113924213  ...                                        NaN
1  113101099  ...                                        NaN
2  113672609  ...                                        NaN
3  115053799  ...                                        NaN
4    6317122  ...                                     116.43

[5 rows x 108 columns]

In [8]:
lending_data.describe()

                 id  ...  orig_projected_additional_accrued_interest
count  7.715900e+04  ...                                 5989.000000
mean   1.152632e+08  ...                                  223.813354
std    2.033129e+07  ...                                  332.369244
min    1.227221e+06  ...                                    0.000000
25%    1.141658e+08  ...                                   27.400000
50%    1.178768e+08  ...                                   97.771770
75%    1.248023e+08  ...                                  304.688880
max    1.264174e+08  ...                                 5321.560000

[8 rows x 88 columns]